# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1773df1d6438f045f4d100f56f0b139009d36d79d6c3da72b38e3620e6a800ede6fa9cd673f56c2170c2e374d0e68222d9431111fbd86a03c35e0f903d0e7b42

test:
  secret_key_base: 68e4a1d201f537e218e86f9c5a32f796eb4da4eeefa12d75d96cfb540e43a78266acb6ddecc5e82254c2a3053db8fe84aaad6eb69992dd56141364c0f661aa7a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
